providers:
  docker:
    exposedByDefault: false
    network: public

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
    http:
      tls:
        certResolver: le

certificatesResolvers:
  le:
    acme:
      email: "timothymardesen@yahoo.com"
      storage: "/acme.json"
      dnsChallenge:
        provider: "duckdns"
        delayBeforeCheck: 0
      httpChallenge:
        entryPoint: web

api:
  insecure: true

log:
  level: info
